// Code generated by genconstraints; DO NOT EDIT.

package domain

const (
	FieldErrorFieldMinLength      = 1
	ItemDescriptionMaxLength      = 2000
	ItemDescriptionPattern        = "^[^\\x00]*$"
	ItemNameMinLength             = 1
	ItemNameMaxLength             = 100
	ItemNamePattern               = "^[^\\x00]*$"
	ItemInputDescriptionMaxLength = 2000
	ItemInputDescriptionPattern   = "^[^\\x00]*$"
	ItemInputNameMinLength        = 1
	ItemInputNameMaxLength        = 100
	ItemInputNamePattern          = "^[^\\x00]*$"
)
