package main

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

func generateGo(constraints []fieldConstraint) (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by genconstraints; DO NOT EDIT.\n\n")
	b.WriteString("package domain\n\n")
	if len(constraints) > 0 {
		b.WriteString("const (\n")
		for _, c := range constraints {
			base := c.Schema + exportName(c.Field)
			if c.MinLength != nil {
				fmt.Fprintf(&b, "\t%sMinLength = %d\n", base, *c.MinLength)
			}
			if c.MaxLength != nil {
				fmt.Fprintf(&b, "\t%sMaxLength = %d\n", base, *c.MaxLength)
			}
			if c.Pattern != "" {
				fmt.Fprintf(&b, "\t%sPattern = %s\n", base, strconv.Quote(c.Pattern))
			}
		}
		b.WriteString(")\n")
	}
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("format generated Go: %w", err)
	}
	return string(formatted), nil
}

func generateTS(constraints []fieldConstraint) string {
	var b strings.Builder
	b.WriteString("// Code generated by genconstraints; DO NOT EDIT.\n\n")
	b.WriteString("export const constraints = {\n")
	for i, c := range constraints {
		if i == 0 || c.Schema != constraints[i-1].Schema {
			if i > 0 {
				b.WriteString("  },\n")
			}
			fmt.Fprintf(&b, "  %s: {\n", c.Schema)
		}
		fmt.Fprintf(&b, "    %s: {\n", c.Field)
		if c.MinLength != nil {
			fmt.Fprintf(&b, "      minLength: %d,\n", *c.MinLength)
		}
		if c.MaxLength != nil {
			fmt.Fprintf(&b, "      maxLength: %d,\n", *c.MaxLength)
		}
		if c.Pattern != "" {
			fmt.Fprintf(&b, "      pattern: %s,\n", strconv.Quote(c.Pattern))
		}
		b.WriteString("    },\n")
	}
	if len(constraints) > 0 {
		b.WriteString("  },\n")
	}
	b.WriteString("} as const;\n")
	return b.String()
}

func exportName(s string) string {
	r, size := utf8.DecodeRuneInString(s)
	if r == utf8.RuneError && size == 0 {
		return s
	}
	return string(unicode.ToUpper(r)) + s[size:]
}
