package main

import (
	"strings"
	"testing"
)

func TestGenerateGo(t *testing.T) {
	src, err := generateGo([]fieldConstraint{
		{Schema: "WidgetInput", Field: "note", MaxLength: intPtr(500)},
		{Schema: "WidgetInput", Field: "title", MinLength: intPtr(2), MaxLength: intPtr(40), Pattern: `^[^\x00]*$`},
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, fragment := range []string{
		"Code generated by genconstraints; DO NOT EDIT.",
		"package domain",
		"WidgetInputNoteMaxLength",
		"= 500",
		"WidgetInputTitleMinLength = 2",
		"WidgetInputTitleMaxLength = 40",
		`"^[^\\x00]*$"`,
	} {
		if !strings.Contains(src, fragment) {
			t.Fatalf("generated Go missing %q:\n%s", fragment, src)
		}
	}
	if strings.Contains(src, "WidgetInputNoteMinLength") {
		t.Fatalf("generated absent minLength: %s", src)
	}
}

func TestGenerateTS(t *testing.T) {
	src := generateTS([]fieldConstraint{
		{Schema: "WidgetInput", Field: "note", MaxLength: intPtr(500)},
		{Schema: "WidgetInput", Field: "title", MinLength: intPtr(2), MaxLength: intPtr(40), Pattern: `^[^\x00]*$`},
	})
	for _, fragment := range []string{
		"Code generated by genconstraints; DO NOT EDIT.",
		"export const constraints = {",
		"WidgetInput: {",
		"note: {",
		"maxLength: 500",
		"title: {",
		"minLength: 2",
		"maxLength: 40",
		`pattern: "^[^\\x00]*$"`,
	} {
		if !strings.Contains(src, fragment) {
			t.Fatalf("generated TS missing %q:\n%s", fragment, src)
		}
	}
}
